sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - EXECUTE_COVERAGE="true"
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: nightly
before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

script:
  - mkdir -p build/logs
  - chmod 777 build/logs
  - if [[ EXECUTE_COVERAGE == "true" ]]; then ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml ; fi
  - if [[ EXECUTE_COVERAGE != "true" ]]; then ./vendor/bin/phpunit ; fi
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyze -c phpstan.neon --level=7 src/

after_script:
  - php vendor/bin/php-coveralls
