name: "Coding Standards"

on:
  pull_request:
    branches:
      - "*.x"
      - "main"
  push:
    branches:
      - "*.x"
      - "main"

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@1.3.0"
    with:
      php-version: '8.0'
      composer-options: '--prefer-dist --ignore-platform-req=php'

