name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
      - "main"
  push:
    branches:
      - "*.x"
      - "main"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
        dependencies:
          - "highest"
        optional-dependencies:
          - true
          - false
        include:
          -   php-version: "8.0"
              dependencies: "lowest"
              optional-dependencies: false
          -   php-version: "8.0"
              dependencies: "lowest"
              optional-dependencies: true

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "pdo_mysql"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        if: "! startsWith(matrix.php-version, '8')"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-suggest"

      - name: "Install dependencies with Composer (--ignore-platform-req=php)"
        uses: "ramsey/composer-install@v1"
        if: "startsWith(matrix.php-version, '8')"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-suggest --ignore-platform-req=php"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ matrix.dbal-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-20.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v2"
        with:
          directory: "reports"
